---
apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrate-{{ .Release.Revision }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    component: db-migrate
spec:
  backoffLimit: 4
  ttlSecondsAfterFinished: 30
  template:
    spec:
      {{- if .Values.imagePullSecret }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret }}
      {{- end }}
      {{- if and .Values.nodeSelector (not .Values.debug) (not .Values.localMode) }}
      nodeSelector:
        {{ .Values.nodeSelector | toYaml }}
      {{- end }}
      restartPolicy: Never
      containers:
      - name: db-migrate
        image: "{{ .Values.api.image }}:{{ .Values.api.tag | default .Values.tag }}"
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        {{- if .Values.localMode }}
        command: ["sh", "-c", "alembic upgrade head && python3 -m anubis.utils.local_bootstrap"]
        {{- else }}
        command: ["alembic", "upgrade", "head"]
        {{- end }}
        env:
        {{- include "api.env" . | nindent 8 }}
---

{{- if and (not .Values.debug) (not .Values.localMode) }}
apiVersion: batch/v1
kind: Job
metadata:
  name: db-visuals-{{ .Release.Revision }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    component: visuals
spec:
  backoffLimit: 4
  ttlSecondsAfterFinished: 30
  template:
    spec:
      {{- if .Values.imagePullSecret }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret }}
      {{- end }}
      {{- if and .Values.nodeSelector (not .Values.debug) (not .Values.localMode) }}
      nodeSelector:
        {{ .Values.nodeSelector | toYaml }}
      {{- end }}
      restartPolicy: Never
      containers:
      - name: visuals
        image: "{{ .Values.api.image }}:{{ .Values.tag }}"
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        command: [ "python3", "anubis/jobs/visuals.py" ]
        env:
        - name: "JOB"
          value: "1"
        {{- include "api.env" . | nindent 8 }}
{{- end }}
